// <auto-generated />
namespace DGSappSem2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StaffnStudentTimetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StaffnStudentTimetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202011092350058_StaffnStudentTimetable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
